---
title: "Aviation Crash Analysis"
output: html_notebook
---

# Import data

```{r}
#install.packages("readr")
library(readr)
library(lubridate)

aero <- read.csv("Airplane_Crashes_and_Fatalities_Since_1908.csv")

```

# check data format

```{r}
str(aero)

```
```{r}
str(aero$Date)
str(aero$Time)
str(aero$Location)
str(aero$Operator)
str(aero$Route)
str(aero$type)
str(aero$Registration)
str(aero$cn.In)
str(aero$Aboard)
str(aero$Fatalities)
str(aero$Ground)
str(aero$Summary)

```




# Changing data types from Char and converting empty strings and dashes to NA

```{r}
aero$Date <- as.Date(aero$Date, format="%m/%d/%Y") # Change Date from a char to Date data type
aero$Time <- lubridate::hm(aero$Time) # Change from char to lubridate

aero$Location <- ifelse(aero$Location == "", NA, aero$Location)
aero$Operator <- ifelse(aero$Operator == "", NA, aero$Operator)
aero$Flight.. <- ifelse(aero$Flight.. == "", NA, aero$Flight..)
aero$Flight.. <- ifelse(aero$Flight.. == "-", NA, aero$Flight..)
aero$Route <- ifelse(aero$Route == "", NA, aero$Route)
aero$Type <- ifelse(aero$Type == "", NA, aero$Type)
aero$Registration <- ifelse(aero$Registration == "", NA, aero$Registration)
aero$cn.In <- ifelse(aero$cn.In == "", NA, aero$cn.In)
aero$Summary <- ifelse(aero$Summary == "", NA, aero$Summary)

```
# Percentage of missing values in each column

```{r}
#aero$Date[aero$Date == ""] <- NA # Fill in empty string with NA
#aero$Date[aero$Date == ""] <- NA # Fill in empty string with NA



#print(aero$Date)
#print(aero$Time)

misscol <- colSums(is.na(aero)) / nrow(aero)
round(misscol, 3)
```

```{r}
na_count1 <- sum(is.na(aero$Date))
na_count2 <- sum(is.na(aero$Time))
na_count3 <- sum(is.na(aero$Operator))
na_count4 <- sum(is.na(aero$Flight..))
na_count5 <- sum(is.na(aero$Route))
na_count6 <- sum(is.na(aero$Type))
na_count7 <- sum(is.na(aero$Registration))
na_count8 <- sum(is.na(aero$cn.In))
na_count9 <- sum(is.na(aero$Aboard))
na_count10 <- sum(is.na(aero$Fatalities))
na_count11 <- sum(is.na(aero$Ground))
na_count12 <- sum(is.na(aero$Summary))



na_count1
na_count2
na_count3
na_count4
na_count5
na_count6
na_count7
na_count8
na_count9
na_count10
na_count11
na_count12
```
# Search for most frequent words in Summary (Text Mining)

```{r}
library(tidytext)
library(dplyr)

aero <- as_tibble(aero)

# Tokenize and count words
word_counts <- aero %>%
  unnest_tokens(word, Summary) %>%  # This function splits the text into individual words.
  count(word, sort = TRUE)          # Count occurrences of each word

print(word_counts)
```

```{r}
# need to sort out NA and make new columns from filtered words
```

